### ISSUE TITLE
搬遷至 GCP

### ISSUE THREAD

**Issue by yc97463** [smhs-os-project/cscheckin-fe#38]

**Comment by pan93412** [comment]
我會 prefer 把前端遷移到 Vercel。

**Comment by swchen1217** [comment]
Vercel 好像只能支援 Github Personal Repo 的專案?

**Comment by pan93412** [comment]
> Vercel 好像只能支援 Github Personal Repo 的專案?

可以申請開源專案，應該是符合資格。此外 Vercel 也接受用 CLI 手動部署。

**Comment by swchen1217** [comment]
> > Vercel 好像只能支援 Github Personal Repo 的專案?
> 
> 可以申請開源專案，應該是符合資格。此外 Vercel 也接受用 CLI 手動部署。

了解，那應該就沒問題
