### ISSUE TITLE
學生在首次輸入班級座號的時候，可以送空值

### ISSUE THREAD

**Issue by yc97463** [smhs-os-project/cscheckin-fe#63]
[https://drive.google.com/file/d/1Xc7NQgzmTGkVoo3vCRo4ZjUnnnMrpTdh/view?usp=drivesdk](https://drive.google.com/file/d/1Xc7NQgzmTGkVoo3vCRo4ZjUnnnMrpTdh/view?usp=drivesdk)

**Comment by pan93412** [comment]
是沒設定吧？現在不會先檢查有沒有設定班級座號了。

**Comment by yc97463** [comment]
⋯？
